title: Hospital Project
logo: /images/logoapp.png
description: This is a Database and Python project. Made by: Isaac Ruiz, Anderson Pérez and Maria del Mar Manzano.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal