remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Hospital Project
description: This is a class project working with Python and PostgreSQL. Made by Isaac Ruiz, Anderson Pérez and Maria del Mar Manzano.